### ISSUE TITLE
When i use gooact, i got some problems

### ISSUE THREAD

**Issue by z2014** [sweetpalma/gooact#1]
this is my [example](https://github.com/z2014/Blog/tree/master/simple-react),this is built in parcel,
and i add "babel-preset-env", and "babel-preset-react", 
but when i run this web, i got this error "React is not defined",
 I wonder why i need react? Or i need extra config?
(I thounght gooact is a simple react, when i use gooact, i don't need React, is that true?)

**Comment by sweetpalma** [comment]
Hello, @z2014, in order to hint Babel which function to use you need to specify it using special comment pragma, try doing it as following:
```
/** @jsx Gooact.createElement */
import Gooact, {render, Component} from 'gooact';
render(<div>Hello World!</div>, document.body);
```

**Comment by sweetpalma** [comment]
Hello, @z2014, in order to hint Babel which function should be used after transpilation you have to use a special pragma comment:
```javascript
/** @jsx yourFunctionToCreateElements */
```
In your specific case code together pragma function will look as following:
```javascript
/** @jsx Gooact.createElement */
import Gooact, {render, Component} from 'gooact';
render(<div>Hello World!</div>, document.body);
```
