### ISSUE TITLE
Incremental setState()

### ISSUE THREAD

**Issue by mindplay-dk** [sweetpalma/gooact#10]
The `setState()` method of `Component` doesn't allow incremental patches to state - this is a pretty substantial inconsistency from React, and it's a one-line fix.

The other example I posted also illustrates this problem:

https://codesandbox.io/s/rwjr4xo47p

```js
    this.onInput = event => {
      this.setState({
        count: this.state.count, // try commenting out this line
        input: event.target.value
      });
    };
```

If you don't explicitly copy over all existing state, it fails, whereas React would internally patch `state` with new properties.

Possible fix: either `Object.assign()` to existing state property, or spread existing properties to an entirely new value, e.g. `{...this.state, new_state}` if you're concerned about possible side-effects.

**Comment by sweetpalma** [comment]
Thanks for reaching out with this one - is it okay now?

**Comment by sweetpalma** [comment]
Accidentally pushed wrong copy, is it okay now?
