### ISSUE TITLE
componentDidMount was called before DOM attached

### ISSUE THREAD

**Issue by vanhtuan0409** [sweetpalma/gooact#3]
Hi, I appreciated your work on explaining React internal.
But I think there is something wrong about life-cycle.
https://gist.github.com/vanhtuan0409/b3bdfb7bfdb50edd45269a95e846c69f
The above snippet shows that `componentDidMount` was called before real DOM is attached to the document.
In the real version of React, I think `componentDidMount` is ensured to be called after the DOM was attached

**Comment by sweetpalma** [comment]
@vanhtuan0409 thanks for notifying me! I did a little investigation and found that source of my inspiration - Preact - had the same issue:
https://github.com/developit/preact/issues/65

I am going to investigate it and try looking for a nice and tiny solution.

**Comment by vanhtuan0409** [comment]
As I think, React split the process into 2 phase. Render phase and Commit phase. Life Cycle might be triggered in Commit phase after the whole DOM tree was constructed.

**Comment by sweetpalma** [comment]
@vanhtuan0409 You're absolutely write - but stuffing stuff in 160 lines of code can be hard sometimes 😄

**Comment by vanhtuan0409** [comment]
Sure It will be too much for a simplified version of React 😃
Tks for the article anyway

**Comment by sweetpalma** [comment]
I think that the most straightforward solution is to defer it for the next cycle using `setTimeout(() => this.componentDidMount(), 0)` - whole tree will be already rendered in that case, but I am not sure if that is the best fix 🤔

**Comment by vanhtuan0409** [comment]
Hey I opened a PR to address this issue https://github.com/sweetpalma/gooact/pull/4
My idea is that we can attach VDOM element as soon as it was created. Then we can incrementally attach its children later.
Not sure if I broke anything, if you have time then take a look

**Comment by sweetpalma** [comment]
Great - I like it, made a few touch ups and added you AUTHORS list. Thanks for contribution!
