### ISSUE TITLE
no ref support

### ISSUE THREAD

**Issue by YutHelloWorld** [sweetpalma/gooact#6]
would upgrade for ref support?

**Comment by sweetpalma** [comment]
I am afraid that I will not able to stuff such complex functionality into current 160 lines - but you can fork it and try making your own implementation by yourself.

**Comment by erdii** [comment]
hey @sweetpalma! nice blog post! :)

i copied your code and played around with it a bit. ref support is actually just 3 more lines:
https://github.com/erdii/vdomact/blob/master/src/lib.ts#L37

**Comment by sweetpalma** [comment]
@erdii Impressive TypeScript implementation! I will review it and try looking how it goes - but not sure if I can stuff that couple of lines 😃

**Comment by sweetpalma** [comment]
@YutHelloWorld @erdii 
After code refactoring I found some spare space - now we have a proper support for "styles" and "ref" attributes in an experimental branch. What do you think guys?
https://github.com/sweetpalma/gooact/tree/experimental-styles-and-refs

**Comment by YutHelloWorld** [comment]
emmm, good works! BTW can we support more features?I would like to do some works :)

**Comment by sweetpalma** [comment]
@YutHelloWorld currently I working on another "fancy thing in 160 lines of javascript" project, now on Node.JS - so I would like to concentrate on it. But if you see any room for improvement - feel free to fork and experiment, it is always a pleasure to contribute together.

**Comment by sweetpalma** [comment]
Rebased into master.

**Comment by erdii** [comment]
@sweetpalma nice!

@YutHelloWorld React's context api would be very nice! I tried to implement it but it was a bit to hard for me.
